version: '3.8'

services:
  db:
    container_name: "linkgraph_postgres"
    image: "postgres:13"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    container_name: "linkgraph_app"
    build: .
    command: >
      bash -c "python /linkgraph/linkgraph/manage.py makemigrations
      && python /linkgraph/linkgraph/manage.py migrate
      && python /linkgraph/linkgraph/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/linkgraph
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: